[program:stub-db_notifications-worker]
process_name=%(program_name)s_%(process_num)02d
command=php /var/www/stub/artisan queue:work --queue=db_notifications
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=root
numprocs=1
redirect_stderr=true
stdout_logfile=/var/www/stub/db_notifications_worker.log
stopwaitsecs=3600
