[program:stub-reverb-server]
process_name=%(program_name)s_%(process_num)02d
command=php /var/www/stub/artisan reverb:start
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=root
numprocs=1
redirect_stderr=true
stdout_logfile=/var/www/stub/reverb_server.log
stopwaitsecs=3600
