[program:stub-scheduled_tasks-worker]
process_name=%(program_name)s_%(process_num)02d
command=php /var/www/stub/artisan queue:work --queue=scheduled_tasks
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=root
numprocs=1
redirect_stderr=true
stdout_logfile=/var/www/stub/scheduled_tasks_worker.log
stopwaitsecs=3600
